### ISSUE TITLE
Laravel PHPUnit Error Event Dispatacher

### ISSUE THREAD

**Issue by iolson** [cartalyst/sentinel#166]
I'm getting a failing test in regards to listing to an event via test class using Laravel. `testSuccessRegister` throws the error below, but the `testFireEvent` works. I was wondering if you knew a way around this, as I want to make sure I have the best test coverage over everything.

```php
<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AuthenticationTest extends TestCase
{
    use DatabaseMigrations;
    use DatabaseTransactions;

    public function testEventFire()
    {
        // Setup expected event.
        $this->expectsEvents(App\Events\User\Registered::class);

        // Create a user.
        $user = factory('App\Models\User')->create();

        // Create activations for users.
        $activation = factory('Cartalyst\Sentinel\Activations\EloquentActivation')->create();

        event(new \App\Events\User\Registered($user, $activation));
    }

    public function testSuccessRegister()
    {
        // Setup expected event.
        $this->expectsEvents(App\Events\User\Registered::class);

        // Setup user data.
        $first_name            = array_get($this->input, 'first_name');
        $last_name             = array_get($this->input, 'last_name');
        $email                 = array_get($this->input, 'email_pass');
        $password              = array_get($this->input, 'password_pass');
        $password_confirmation = array_get($this->input, 'password_pass');

        // Perform POST
        $this->post('/api/v1/auth/register', compact('first_name', 'last_name', 'email', 'password', 'password_confirmation'));
    }
}
```

```
[2015-12-13 00:46:48] testing.ERROR: exception 'ErrorException' with message 'Argument 5 passed to Cartalyst\Sentinel\Sentinel::__construct() must be an instance of Illuminate\Events\Dispatcher, instance of Mockery_0_Illuminate_Contracts_Events_Dispatcher given, called in /home/vagrant/Projects/<project>/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php on line 342 and defined' in /home/vagrant/Projects/<project>/vendor/cartalyst/sentinel/src/Sentinel.php:134
```

**Comment by suwardany** [comment]
Hello @iolson 

Could you email us a copy of the test case and any relevant files? I'll look into it.

**Comment by suwardany** [comment]
should be fixed on the [feature/dispatcher-contract](https://github.com/cartalyst/sentinel/tree/feature/dispatcher-contract) branch

**Comment by iolson** [comment]
Was wondering if this was going to get merged into release at all?

**Comment by brunogaspar** [comment]
I'm "fine" with the merge, but we need to keep in mind that it introduces a breaking change, a small one, but it's still a breaking change.

**Comment by JVMartin** [comment]
This is still an issue, why can't this be fixed to support Laravel testing?
